### PR TITLE
fix(transition): transition to expand component in development

### LINKED ISSUE #256: Transition for expandable components doesn't work in proper way in development.
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

### Describe the bug
In development expandable components expand transition doesn't work properly.
Delete react strict mode to could help to check how it works in production.

### To reproduce

1. Go to Components from the menu.
2. Choose Expandable or ExpandableList.
3. Click arrow button to expand and collapse the component.

### Screenshots
Peek 2023-02-10 16-19

### Environment

- Axis device model: [e.g. Q1615 Mk III]
- Axis device firmware version: [e.g. 10.5]
- Stack trace or logs: [e.g. Axis device system logs]
- OS and version: [e.g. macOS v12.2.1, Ubuntu 20.04 LTS, Windows build 21996.1]
- Version: [version of the application, SDK, runtime environment, package manager, interpreter, compiler, depending on what seems relevant]

### PR DESCRIPTION
**Pull request by Sana-Shana**
### Describe your changes

Fix transition animation for expandable components in development.
Set only the initial offsetHeight of html elements for increaseHeight,
because in development when react runs in strict mode, the height of the component is set twice.

Also, create a [bug report](https://github.com/AxisCommunications/practical-react-components/issues/256)

### Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have verified that the code builds perfectly fine on my local system
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have verified that my code follows the style already available in the repository
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/core/src/Transition/FoldTransition.tsx [hunk 1]
```diff
@@ -35,6 +35,7 @@ export const FoldTransition: FC<FoldTransitionProps> = ({
     const node = nodeRef.current
 
     const height = node.offsetHeight
+    if (height === 0) return
```
Comment (boilund) [inline packages/core/src/Transition/FoldTransition.tsx:38]: It seems like the problem is the `increaseHeight` function is called twise when it opens. Do you know why? If it is called once, I think you don't need to add this line.

Comment (Sana-Shana) [reply packages/core/src/Transition/FoldTransition.tsx:38]: I am not sure exactly, but when I take away react strict mode, it stops running twice.

Comment (boilund) [reply packages/core/src/Transition/FoldTransition.tsx:38]: Ok! I can approve this when you change the commit message.

**Review by boilund — APPROVED** [review]
